### ISSUE TITLE
Loggly "invalid response packet" issue

### ISSUE THREAD

**Issue by mtyurt** [cboscolo/elb2loggly#2]
Hello, I have managed to setup the lambda script. The issue I have is, Loggly shows following error as event each time a log file is uploaded:

```
LogglyNotifications:
    syslog:
        severity: Warning
        appName: avahi-daemon
        timestamp: 2015-07-07T14:41:19.706596+03:00
        facility: system daemons
        pid: 970
        priority: 28
        host: linux
unparsed:
    message: Invalid response packet from host 192.168.2.112.
Raw Message:
    Invalid response packet from host 192.168.2.112.
```

What is the problem here?
